
Vagrant.configure("2") do |config|
  BOX_NAME = "debian/bookworm64"
  VM_MEMORY = 1024
  VM_CPUS = 1
  config.vm.define "ealtinorS" do |server|
    server.vm.box = BOX_NAME
    server.vm.hostname = "ealtinorS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = VM_MEMORY
      vb.cpus = VM_CPUS
    end
    server.vm.provision "shell", inline: <<-SHELL
      bash /vagrant/scripts/init-vm.sh
      bash /vagrant/scripts/k3s-server.sh
      bash /vagrant/scripts/kubectl-apply.sh
    SHELL
  end
end