apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ensaltnrk/InceptionOfThings
    targetRevision: HEAD
    path: p3/conf/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true