
Vagrant.configure("2") do |config|
  BOX_NAME = "debian/bookworm64"
  VM_MEMORY = 4096
  VM_CPUS = 4
  config.vm.define "ealtinorS" do |server|
    server.vm.box = BOX_NAME
    server.vm.hostname = "ealtinorS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = VM_MEMORY
      vb.cpus = VM_CPUS
    end
  end
end